
from rsf.proj import *

Flow(['gather_subset.rsf','gather_subset_hdr.rsf'],
     ['../../data/cmp/npr3_gathers.rsf','../../data/cmp/npr3_gathers_hdr.rsf'],
     '''

sftahsort
        input=$SOURCE
        sort="iline:169,181  xline:104,116 offset:0,11000"
        verbose=1



     sftahsort
        input=$SOURCE
        sort="iline:169,181  xline:104,116 offset:0,11000"
        verbose=1
     | sftahmakeskey pkey=iline,xline skey=cdpt verbose=1
     | sftahwrite
        verbose=1
        label2="cdpt"  o2=1 n2=34  d2=1
        label3="xline" o3=104 n3=1 d3=1
        label4="iline" o4=169 n4=1  d4=1
        output=$TARGET
      ''',stdout=0,stdin=0)

Plot('gather_subset', 'grey  title="Gather"',view=1)

sfwiggle < gather_subset.rsf fatp=1 xmask=1 ymask=1 pclip=98. zplot=0.75 clip=0. seemean=n verb=n transp=n yreverse=n xreverse=n > plot.vpl

End()

