from rsf.proj import *
import os

import os
import fnmatch
def sgy2rsf(input_dir, output_dir):

    if not os.path.exists(output_dir):
        os.makedirs(output_dir)

    for f in fnmatch.filter(os.listdir(input_dir),
                            '*.sgy'):

        filebase = os.path.join(output_dir,
                                os.path.splitext(f)[0])
        
        infile = os.path.join(input_dir, f)

        headers = [filebase + ext  for ext in
               ['.rsf','_hdr.rsf', 
                '.thdr','.bhdr']]

        Flow(headers, infile,
             '''
             sfsegyread tfile=${TARGETS[1]} 
             hfile=${TARGETS[2]}  bfile=${TARGETS[3]} 
             ''')

        Flow(os.path.join(output_dir,'headerattr.txt'),
             headers[1],
             'sfheaderattr > $TARGET && /bin/cat $TARGET',stdout=-1)

sgy2rsf('../../data/cmp', '../../data/cmp')
sgy2rsf('../../data/field', '../../data/field')

output_dir = '../../docs'

if not os.path.exists(output_dir):
    os.makedirs(output_dir)

pdfread = WhereIs('acroread') or WhereIs('kpdf') or WhereIs('evince') or \
    WhereIs('xpdf') or WhereIs('gv') or WhereIs('open')

# download and view the survey notes:
Fetch('3dload_Teapot_Dome_3D.pdf','teapot',
      server='http://s3.amazonaws.com',top='')
Flow('3dload','3dload_Teapot_Dome_3D.pdf',
     pdfread + ' $SOURCE',stdin=0, stdout=-1)
Fetch('teapot_processing.pdf','teapot',
      server='http://s3.amazonaws.com',top='')
Flow('processing','teapot_processing.pdf',
     pdfread + ' $SOURCE',stdin=0,stdout=-1)

os.system('mv *.pdf ' + output_dir)
    
End()
