from rsf.proj import *

Flow(['gather_subset.rsf','gather_subset_hdr.rsf'],
     ['../../data/cmp/npr3_gathers.rsf','../../data/cmp/npr3_gathers_hdr.rsf'],
     '''
     sftahsort
        input=$SOURCE
        sort="iline:169,181  xline:104,116 offset:0,11000"
        verbose=1
     | sftahmakeskey pkey=iline,xline skey=cdpt verbose=1
     | sftahwrite
        verbose=1
        label2="cdpt"  o2=1 n2=34  d2=1
        label3="xline" o3=104 n3=1 d3=1
        label4="iline" o4=169 n4=1  d4=1
        output=$TARGET
      ''',stdout=0,stdin=0)

Flow('offset','../../fetch/npr3_gathers_hdr.rsf',
     'window n1=1 f1=11 squeeze=n | intbin3 head=$SOURCE xkey=-1 | dd type=float')

Flow('offset1','offset', 'window n3=1 n4=1 f3=120 f4=140')

Flow('vscan','gather_subset offset1','vscan offset=${SOURCES[1]} v0=9000 nv=101 dv=100 semblance=y half=n nb=10')

Plot('vscan', 'grey color=j title="Semblance Scan" unit2=ft/s',view=1)

End()
