import os
from rsf.proj import *

infile = "../../processed/nmo/npr3_gathers.rsf"
inhdr = "../../processed/nmo/npr3_gathers.rsf"
output_dir = "../../processed/offset_stack"

offsets = [('0','3000'), ('3000','6000'), ('6000','9000')]

if not os.path.exists(output_dir):
    os.makedirs(output_dir)

for stack in offsets:
    
    offset_string = str(stack[0]) + '_' + str(stack[1])
    filebase = os.path.splitext(os.path.basename(infile))[0]
    
    output = os.path.join(output_dir, offset_string + '_' + filebase + '.rsf')
    output_hdr = os.path.join(output_dir, offset_string + '_' + filebase + '_hdr.rsf')

    Flow([output, output_hdr], [infile, inhdr],
         """
         sftahsort
         input=$SOURCE
         sort="iline:1,181  xline:1,356 offset:""" + ','.join(stack) + """"
         | sftahstack key=cdp |
         sftahwrite
         label2="xline" o2=1 n2=345 d2=1   \
         label3="iline" o3=1 n3=188 d3=1   \
        output=${TARGETS[0]}
         outheaders=${TARGETS[1]}""", stdout=0, stdin=0)
         
    

