from rsf.proj import *

Flow('foldplot','../Fetchpaper/npr3_field_hdr.rsf',
    '''
      sfdd type=float |
      sffold
          verbose=1
          o1=0 n1=96  d1=200 label1=offset
          o2=1 n2=188 d2=1   label2=xline
          o3=1 n3=345 d3=1   label3=iline        
    ''')

End()
